# Generated by Django 4.1.7 on 2023-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_contact_remove_order_cart_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма заказа'),
            preserve_default=False,
        ),
    ]
