# Generated by Django 4.1.7 on 2023-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Почта для подписки',
                'verbose_name_plural': 'Почты для подписки',
            },
        ),
    ]
